spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 9ECSQl7N
    url: jdbc:postgresql://10.19.132.205:7017/spfd_spfddb?nullCatalogMeansCurrent=true
    username: postgres
  #  redis:
  #    port: 6379
  #    timeout: 5000
mybatis-plus:
  config-location: classpath:MybatisConfig.xml
  mapper-locations: classpath:mapper/*.xml
#debug: true
server:
  port: 8099
